### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by AttilaThePunn** [BardezAnAvatar/Sots.Sots1.SavedGameEditor#44]
Really dumb question, I can't find a way to actually run release 1.4.0 or 1.4.1, are they meant to have executables or am I just stupid?

**Comment by BardezAnAvatar** [comment]
No problem. I'm trying to get 2.0.0 out the door at the moment. It looks like some fuckery was going on with the build action for [1.4.1](https://github.com/BardezAnAvatar/Sots.Sots1.SavedGameEditor/releases/tag/v1.4.1) -- the executable wasn't compiling properly, but the build action reported success.

New build pipeline is actually building on .NET 8 correctly, so I think that will work properly.

**Comment by BardezAnAvatar** [comment]
> Done Building Project "D:\a\Sots.Sots1.SavedGameEditor\Sots.Sots1.SavedGameEditor\Bardez.Project.SwordOfTheStars.IO\Bardez.Project.SwordOfTheStars.IO.csproj" (default targets) -- FAILED.

![image](https://github.com/BardezAnAvatar/Sots.Sots1.SavedGameEditor/assets/39980629/cefc0108-9e31-4d16-aaa0-88a52b1844b1)

**Comment by BardezAnAvatar** [comment]
OK, check out [sots-sge_v2.0.0.zip](https://github.com/BardezAnAvatar/Sots.Sots1.SavedGameEditor/releases/download/v2.0.0/sots-sge_v2.0.0.zip). I just downloaded and unzipped it, it's working fine locally for me.

I've about to see how well/badly the latest works on Steam Deck :)

**Comment by AttilaThePunn** [comment]
> No problem. I'm trying to get 2.0.0 out the door at the moment. It looks like some fuckery was going on with the build action for [1.4.1](https://github.com/BardezAnAvatar/Sots.Sots1.SavedGameEditor/releases/tag/v1.4.1) -- the executable wasn't compiling properly, but the build action reported success.
> 
> New build pipeline is actually building on .NET 8 correctly, so I think that will work properly.

Awesome! Thanks for answering, I love seeing people still working on this game. Great work!

**Comment by BardezAnAvatar** [comment]
SotS is a personal favorite of mine. This editor is at least 13 years old; I just ran into a tech block on Steam Deck and figured when it didn't run that it was time to spruce it up.

Feel free to report issues; preferably include your save file so I have more test data to debug.
